name: CI

on:
  push:
    branches: ['**']        # läuft bei jedem Branch
  pull_request:
    branches: ['**']        # läuft bei jedem PR
  workflow_dispatch:         # manuell startbar

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python env (debug)
        run: |
          which python
          python --version
          python -m pip --version

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install pytest flake8

      - name: Verify pytest installation (debug)
        run: |
          python -c "import sys, platform, importlib; print('exe:', sys.executable); print('plat:', platform.platform()); importlib.import_module('pytest'); print('pytest OK')"

      - name: Lint (flake8)
        run: |
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          python -m pytest -q
